### ISSUE TITLE
docker-compose up is taking very long 

### ISSUE THREAD

**Issue by BabylonCoder** [daq-tools/kotori#104]
Hi, anyone know why the docker-compose up is taking ages to unpack the Mosquitto, InfluxDB, MongoDB and Grafana ? is that normal ? I have MacOs BigSur ! thank you

**Comment by BabylonCoder** [comment]
Sorted, this was my installation method

**Comment by amotl** [comment]
Hi @BabylonCoder,

apologies for the late reply. Did you manage to get the stack running properly in the end? Please let me know if you need further assistance, and if you find any bugs or spots for improvement.

With kind regards,
Andreas.

**Comment by BabylonCoder** [comment]
Hi @amotl; all good. It was my installation. It would be great, though,  to do a detailed; video so we can learn more and also so I can teach it to my class at university. Thank you for a great product.
